version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
      - netbsd

archives:
  - format: binary
    name_template: "{{ .Os }}-{{ .Arch }}"

changelog:
  use: github-native
